


apabinary : apabinary.c
	gcc apabinary.c -o apabinary -lm
	./apabinary
	pcbnew apabinary.kicad_pcb


clean :
	rm -f apabinary
	#rm -f *.kicad_pcb
	rm -f *.kicad_pcb-bak
	rm -f *.pro
	rm -f fp-info-cache



