


clock61.kv3 : clock61.kv3.c
	gcc clock61.kv3.c -o clock61.kv3 -lm
	./clock61.kv3
	pcbnew clock61.kv3.kicad_pcb


clean :
	rm -f clock61.kv3
	#rm -f *.kicad_pcb
	rm -f *.kicad_pcb-bak
	rm -f *.pro



